repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.4
    hooks:
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_checkov
      - id: terraform_docs
