enableGitInfo   = true
baseURL = "https://devopsloop.in/"
languageCode = 'en-us'
title = 'devopsloop'
theme = 'hello-friend-ng'
sectionPagesMenu = 'main'
contentDir = 'content'
enableEmoji    = true
disableRSS     = false
disableSitemap = false

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.

[params]
  dateform        = " 2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"
  gitUrl = 'https://github.com/devopsloop-ss/devopsloop/commits/'

  # Subtitle for home
  homeSubtitle = "A blog by a DevOps engineer"

  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "A Blog about DevOps Journey, tools and tech"
  keywords = "homepage, blog"
  images = [""]

  justifyContent = true

  [[params.author]]
    name = "Shubham"

  [params.footer]
    trademark = 2024
    rss = false
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://linkedin.com/in/shubham-om-sinha\">Shubham</a>",
      "hugo theme: <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello friend ng</a>"
    ]

  # Social icons

  [[params.social]]
    name = "email"
    url  = "mailto:shubham@devopsloop.in"

  [[params.social]]
    name = "github"
    url  = "https://github.com/devopsloop-ss/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/shubham-om-sinha"


[permalinks]
  posts = "/posts/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
[languages]
  [languages.en]
    title = "This is DevOpsloop"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


  [languages.en.params]
    subtitle  = "A DevOps Odyssey"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
    #  logoText = "devopsloop"
      logoHomeLink = "/"
    # or
    #
      path = "/img/devopsloop-new.png"
      alt = "devopsloop"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "profile"
    name       = "About me"
    url        = "/profile"

[deployment]
  [[deployment.targets]]
    name = "prod"
    URL  = "s3://site-prod-devopsloop-site-origin?region=us-east-1"
